### ISSUE TITLE
LandScan Data Access

### ISSUE THREAD

**Issue by aseemdeodhar** [Streets-Data-Collaborative/BostonSidewalks#2]
LandScan requires an active affiliation with an educational institute to download their data. I've created an account, now waiting for authorization. I'm currently using block level 2010 census data until then.

**Comment by aseemdeodhar** [comment]
I finally got access to the LandScan data, however it is not loading in ArcPro. When I *add data* I am getting error saying
![image](https://user-images.githubusercontent.com/39370828/86822274-6954aa00-c059-11ea-95a2-c2039c154b62.png)

**Comment by vr00n** [comment]
Try this?

https://geoplatform.maps.arcgis.com/home/item.html?id=e431a6410145450aa56606568345765b

**Comment by aseemdeodhar** [comment]
@vr00n yep. Found that last night as well!

https://hifld-geoplatform.opendata.arcgis.com/datasets/landscan-usa

Clipped the data to Boston/Suffolk County and vectorized. Displaying daytime population on log scale.

![image](https://user-images.githubusercontent.com/39370828/86932908-f2c2b580-c107-11ea-816f-ddd0b5351baf.png)
